apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: clone-build-push-binding
  namespace: tekton-pipelines  # <-- Change the namespace
spec:
  params:
    - name: repo-url
      value: https://github.com/arunvel1988/docker_app_ci
    - name: image-reference
      value: arunvel1988/docker_app_ci_2025-march