[ec2-user@ip-172-31-42-95 enfore-event-listener-service-account]$ cat policy.yml 
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-eventlistener-serviceaccount
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-non-default-serviceaccount
      match:
        any:
          - resources:
              kinds:
                - EventListener
      validate:
        message: "EventListeners must specify a non-default serviceAccountName."
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.serviceAccountName }}"
                operator: Equals
                value: "default"
              - key: "{{ request.object.spec.serviceAccountName }}"
                operator: Equals
                value: ""