apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: my-listener
spec:
  triggers:
    - name: my-trigger
      bindings:
        - ref: my-triggerbinding
      template:
        ref: my-triggertemplate